name: MCMurder
author: CactusPuppy
main: com.github.cactuspuppy.mcmurder.Main
version: 0.1.5
api-version: '1.14'
permissions:
  murder.admin:
    description: "Allows the holder to interface with the plugin"
    # TODO
